language: rust
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - name: "master doc to gh-pages"
      rust: nightly
      script:
        - cargo doc --no-deps
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        skip_cleanup: true
        on:
          branch: master
script:
  - cargo build --verbose
  - cargo test --verbose
  # Tests with no_core
  - |
    if [ "${TRAVIS_RUST_VERSION}" == "nightly" ]; then
      cargo build --verbose --no-default-features
    fi

notifications:
  email:
    on_success: never
